# Generated by Django 5.0.1 on 2024-02-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_image',
            field=models.ImageField(default='place/notphoto.jpg', upload_to='place/'),
        ),
    ]
