# Generated by Django 5.0.1 on 2024-02-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_place_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_image',
            field=models.ImageField(default='place/nophoto.jpg', upload_to='place/'),
        ),
    ]
