# Generated by Django 5.0.1 on 2024-02-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profiles/notphoto.jpg', upload_to='profiles/'),
        ),
    ]
