# Generated by Django 5.0.1 on 2024-02-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='place',
            new_name='location',
        ),
    ]
