# Generated by Django 5.0.1 on 2024-03-13 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_place_places_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'локацию', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='places',
            name='creates',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='places',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Впечатление'),
        ),
        migrations.AlterField(
            model_name='places',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='places',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='places',
            name='place_image',
            field=models.ImageField(default='places/window.jpg', upload_to='places/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мой город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profiles/notphoto.jpg', upload_to='profiles/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Логин'),
        ),
    ]
