# Generated by Django 5.0.1 on 2024-03-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_places_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name'], 'verbose_name': 'профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
