# Generated by Django 5.0.1 on 2024-04-21 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.CreateModel(
            name='TravelDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место отдыха')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Когда приехали?')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Когда уехали?')),
                ('tickets_to_and_from', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Стоимость билетов туда и обратно')),
                ('cafes', models.TextField(blank=True, null=True, verbose_name='Кафе и рестораны')),
                ('housing', models.CharField(max_length=100, verbose_name='Где остановились?')),
                ('entertainments', models.TextField(blank=True, null=True, verbose_name='Развлечения')),
                ('transportation_costs', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Потрачено на транспорт')),
                ('travel_image', models.ImageField(default='travels/window.jpg', upload_to='travels/', verbose_name='Фото')),
                ('money_spend_on_eats', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Потрачено на еду')),
                ('money_spend_on_housing', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Потрачено на жилье')),
                ('money_spend_on_entertainments', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Потрачено на развлечения')),
                ('history', models.JSONField(default=dict, verbose_name='История путешествия')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'путешествие',
                'verbose_name_plural': 'Дневник путешествий',
            },
        ),
    ]
