# Generated by Django 5.0.1 on 2024-04-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_verification_user_traveldiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveldiary',
            name='history',
        ),
    ]
