# Generated by Django 5.0.1 on 2024-05-15 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_traveldiary_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_more_photo', models.ImageField(blank=True, null=True, upload_to='travels/add/', verbose_name='Изображение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Кто создал')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.traveldiary', verbose_name='Путешествие')),
            ],
            options={
                'verbose_name': 'ещё изображение',
                'verbose_name_plural': 'Ещё изображения',
            },
        ),
    ]
