# Generated by Django 5.0.1 on 2024-05-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_morephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MorePhoto',
        ),
    ]
