# Generated by Django 5.0.1 on 2024-03-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_festival'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
