# Generated by Django 5.0.1 on 2024-03-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_alter_city_options_alter_excursions_options_and_more'),
        ('events', '0004_festival_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festival',
            options={'ordering': ['date_of_the'], 'verbose_name': 'фестиваль', 'verbose_name_plural': 'Фестивали'},
        ),
        migrations.AlterModelOptions(
            name='lifehacks',
            options={'ordering': ['created'], 'verbose_name': 'лайфхак', 'verbose_name_plural': 'Лайфхаки'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created'], 'verbose_name': 'новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='festival',
            name='css',
            field=models.CharField(default='-', max_length=200, verbose_name='CSS класс'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='date_of_the',
            field=models.DateField(verbose_name='Когда?'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='info',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lifehacks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='lifehacks',
            name='description',
            field=models.TextField(max_length=600, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lifehacks',
            name='featured_image',
            field=models.ImageField(upload_to='lifehacks/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='lifehacks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='new_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
