# Generated by Django 5.0.1 on 2024-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_festival_options_alter_lifehacks_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Месяца')),
                ('css', models.CharField(default='-', max_length=200, verbose_name='CSS класс')),
                ('dt_f', models.CharField(default='-', max_length=200, verbose_name='data-f')),
            ],
            options={
                'verbose_name': 'месяца',
                'verbose_name_plural': 'Месяц',
            },
        ),
    ]
