# Generated by Django 5.0.1 on 2024-03-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypesRecreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Виды отдыха')),
            ],
            options={
                'verbose_name': 'вид',
                'verbose_name_plural': 'Виды отдыха',
            },
        ),
    ]
