# Generated by Django 5.0.1 on 2024-03-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('tour_images', models.ImageField(default='tour_images/trending-1.jpg', upload_to='tour_images/', verbose_name='Изображение')),
                ('preview', models.CharField(max_length=300, verbose_name='Превью')),
                ('program', models.TextField(blank=True, verbose_name='Программа тура')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Продолжительность')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directions.typesrecreation', verbose_name='Вид отдыха')),
            ],
            options={
                'verbose_name': 'тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
