# Generated by Django 5.0.1 on 2024-03-31 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_tours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_photo', models.ImageField(blank=True, upload_to='tour_images/add/', verbose_name='Изображение')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directions.tours', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
