# Generated by Django 5.0.1 on 2024-04-02 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('order_email', models.CharField(max_length=100, verbose_name='Почта')),
                ('order_tel', models.CharField(max_length=100, verbose_name='Телефон')),
                ('order_nik_tg', models.CharField(max_length=100, verbose_name='Ник в телеграмме')),
                ('order_people', models.PositiveIntegerField(default=0, verbose_name='Кол-во человек')),
                ('order_date', models.DateField(verbose_name='Когда?')),
                ('order_tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directions.tours', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
