# Generated by Django 5.0.1 on 2024-04-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда?'),
        ),
    ]
