# Generated by Django 5.0.1 on 2024-04-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0005_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Когда?'),
        ),
    ]
