# Generated by Django 5.0.1 on 2024-04-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0007_alter_order_order_date'),
        ('users', '0011_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('value', models.CharField(choices=[('1', 'one star'), ('2', 'two stars'), ('3', 'three stars'), ('4', 'four stars'), ('5', 'five stars')], max_length=50, verbose_name='Сколько звезд')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Кто оставил')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directions.tours', verbose_name='Какой тур')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
                'unique_together': {('owner', 'tour')},
            },
        ),
    ]
