# Generated by Django 5.0.1 on 2024-04-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='all_stars',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Сколько звезд'),
        ),
        migrations.AddField(
            model_name='review',
            name='percent_stars',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Средняя звезда'),
        ),
    ]
