# Generated by Django 5.0.1 on 2024-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0009_review_all_stars_review_percent_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='all_stars',
        ),
        migrations.RemoveField(
            model_name='review',
            name='percent_stars',
        ),
        migrations.AddField(
            model_name='tours',
            name='all_stars',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=range(1, 5)),
        ),
        migrations.AddField(
            model_name='tours',
            name='percent_stars',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Средняя звезда'),
        ),
    ]
