# Generated by Django 5.0.1 on 2024-04-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0010_remove_review_all_stars_remove_review_percent_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='all_stars',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сколько звезд'),
        ),
    ]
