# Generated by Django 5.0.1 on 2024-04-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0011_alter_tours_all_stars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tours',
            options={'ordering': ['-percent_stars', '-all_stars'], 'verbose_name': 'тур', 'verbose_name_plural': 'Туры'},
        ),
    ]
