# Generated by Django 5.0.1 on 2024-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0012_alter_tours_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('0', '★'), ('1', '★★'), ('2', '★★★'), ('3', '★★★★'), ('4', '★★★★★')], max_length=50, verbose_name='Сколько звезд'),
        ),
    ]
