# Generated by Django 5.0.1 on 2024-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0017_alter_tours_options_remove_tours_all_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Рейтинг'),
        ),
    ]
