# Generated by Django 5.0.1 on 2024-04-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0018_tours_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='all_rat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
