# Generated by Django 5.0.1 on 2024-04-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0019_tours_all_rat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='all_rat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tours',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
