# Generated by Django 5.0.1 on 2024-03-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_options_excursions_excursions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='excursions_image',
            field=models.ImageField(blank=True, default='excursions/excursions.jpg', null=True, upload_to='excursions/'),
        ),
    ]
