# Generated by Django 5.0.1 on 2024-03-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_city_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['title'], 'verbose_name': 'город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='excursions',
            options={'ordering': ['-price'], 'verbose_name': 'экскурсию', 'verbose_name_plural': 'Экскурсии'},
        ),
        migrations.AlterField(
            model_name='city',
            name='city_image',
            field=models.ImageField(default='cities/window.jpg', upload_to='cities/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='city',
            name='info',
            field=models.TextField(blank=True, verbose_name='информация'),
        ),
        migrations.AlterField(
            model_name='city',
            name='link_site_city',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='сайт города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='preview',
            field=models.TextField(blank=True, null=True, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='excursions_image',
            field=models.ImageField(blank=True, default='excursions/excursions.jpg', null=True, upload_to='excursions/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
