# Generated by Django 5.0.1 on 2024-03-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_alter_city_options_alter_excursions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursions',
            options={'ordering': ['price', 'duration'], 'verbose_name': 'экскурсию', 'verbose_name_plural': 'Экскурсии'},
        ),
    ]
