# Generated by Django 5.0.2 on 2024-02-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_one', models.TextField(blank=True, null=True)),
                ('description_two', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(default='matreshka.png', upload_to='index/%Y/%n/%d')),
                ('demo_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='index.tag')),
            ],
        ),
    ]
