# Generated by Django 5.0.1 on 2024-02-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='featured_image',
            field=models.ImageField(default='matreshka.png', upload_to='index/%Y/%m/%d/'),
        ),
    ]
