# Generated by Django 5.0.1 on 2024-03-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_paper_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['title'], 'verbose_name': 'статью', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
