# Generated by Django 5.0.1 on 2024-04-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgsettings',
            name='tg_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='tgsettings',
            name='tg_chat',
            field=models.CharField(max_length=200, verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='tgsettings',
            name='tg_token',
            field=models.CharField(max_length=200, verbose_name='Токен'),
        ),
    ]
